### ISSUE TITLE
Add-ons do not generate source maps

### ISSUE THREAD

**Issue by olivierlesnicki** [gdub22/ember-cli-less#24]
I've created an add-on that uses ember-cli-less and addon.less file
I've added the add-on in my app (which also uses ember-cli-less with sourcemaps enabled)

I get the following not found issue:
```
http://localhost:4200/assets/addon.css.map 
```

**Comment by gdub22** [comment]
Will investigate what's creating that request.  A source map shouldn't be generated for an addon that's included in an app.  It should get concatenated into vendor.css and a source map generated for vendor.

**Comment by gdub22** [comment]
I can't reproduce the error message.  A less addon should not and does not create a source map because it gets concat'ed into the parent app's vendor.css.  Also, contrary to my last comment, a source map isn't created for vendor.css because it can be build with a combination of different preprocessors.
