### ISSUE TITLE
Usage in Addon

### ISSUE THREAD

**Issue by svkangal** [gdub22/ember-cli-less#40]
I am new to this whole Ember Addon stuff, would it work with addon if we add list it as a devdependancy instead? Problem of it being a dependancy is that it will get linked in to the consuming app as a dependancy.

**Comment by knownasilya** [comment]
Totally fine, as long as you build your assets before hand, i.e. commit your `dist` folder.

**Comment by knownasilya** [comment]
What are you trying to do with less in your addon?

**Comment by svkangal** [comment]
https://github.com/gdub22/ember-cli-less#usage-in-addons, My addon styles are in less, want to convert them to css when anyone uses the addon.

**Comment by knownasilya** [comment]
As far as I'm aware, you must put it in the dependencies otherwise it won't be installed when a user installs your addon, since devDependencies are only installed when you do `npm install` from within the project folder. Also, I don't think that the addon will be a direct dependency of the users project, since it's not defined in their package.json so ember-cli doesn't pick it up.

**Comment by svkangal** [comment]
Thanks for replying. Right now its confusing on what is the right way to include styles and the discussion over here also got me confused. 
https://github.com/ember-cli/ember-cli/issues/1853

**Comment by knownasilya** [comment]
For addons I usually import inside the `index.js` in the `included` hook. I think that works with the preprocessor if it's in the deps.

**Comment by knownasilya** [comment]
I'm going to close this, feel free to continue asking questions here (related to this topic).

**Comment by svkangal** [comment]
Thanks for the help
